apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fips-pipeline-task
spec:
  params:
    - description: 'OCP major version, eg: 4.15'
      name: version
      type: string
    - description: 'Space separated NVRs'
      name: nvrs
      type: string
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/art-cd/art-cd:latest
      name: run-script
      resources: {}
      script: |
        #!/usr/bin/env bash

        set -e

        touch /root/.config/artcd.toml

        kinit -kt /tmp/keytab/keytab exd-ocp-buildvm-bot-prod@IPA.REDHAT.COM
        
        pip install stomp.py==8.1.0
        pip install setuptools==70.0.0

        artcd -vv --dry-run scan-fips --all-images

      securityContext:
        runAsGroup: 0
        runAsUser: 0
        privileged: true
      volumeMounts:
        - mountPath: /root/.config/art-bot
          name: art-bot-docker-config
        - mountPath: /root/.config/doozer
          name: doozer-config
        - mountPath: /tmp/keytab
          name: synced-exd-ocp-buildvm-bot-prod-keytab
      env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: art-bot-config
              key: slack-api-token
  volumes:
    - name: art-bot-docker-config
      secret:
        secretName: art-bot-docker-config
    - name: doozer-config
      secret:
        secretName: doozer-config
    - name: synced-exd-ocp-buildvm-bot-prod-keytab
      secret:
        secretName: synced-exd-ocp-buildvm-bot-prod-keytab
