apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-list-rolebinding
  namespace: art-cd
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: art-cd
roleRef:
  kind: Role
  name: pipeline-list-role
  apiGroup: rbac.authorization.k8s.io
