kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: validator
  namespace: art-ci
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'validator:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: ocp-build-data-validator/Dockerfile
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi9/ubi-minimal
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-eng/art-tools'
      ref: main
    contextDir: /
  runPolicy: Serial
