kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggers-validator-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: art-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
