apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-validator
  namespace: art-ci
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: github-pr-url
      template:
        ref: trigger-template-validator-pipeline
