kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: validator
  namespace: art-ci
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi9/ubi-minimal:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
