apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validator-task
  namespace: art-ci
spec:
  params:
    - name: PR_link
      type: string
  steps:
    - command:
        - sh
        - entrypoint.sh
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: powerful
              name: github-token
        - name: PR_URL
          value: $(params.PR_link)
      image: 'image-registry.openshift-image-registry.svc:5000/art-ci/validator:latest'
