apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-validator-pipeline
  namespace: art-ci
spec:
  params:
    - name: git-pr-url
    - name: git-pr-action
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: validator-pipeline-from-trigger-
        labels:
          tekton.dev/pipeline: validator-pipeline
        namespace: art-ci
      spec:
        params:
          - name: pr_url
            value: $(tt.params.git-pr-url)
          - name: pr_action
            value: $(tt.params.git-pr-action)
        pipelineRef:
          name: validator-pipeline
