apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-url
  namespace: art-ci
spec:
  params:
    - name: git-pr-url
      value: $(body.pull_request.html_url)
    - name: git-pr-action
      value: $(body.action)
